[workspace]


[package]
name = "rando_shuffler"
version = "0.1.0"
authors = ["berylliosis <berylliumninja@gmail.com>"]
edition = "2021"

[dependencies]
petgraph = "0.5.1"
rando_parser = { path = "rando_parser" }
rando_core = { path = "rando_core" }
regex = "1"
codespan-reporting = "0.11.1"