[package]
name = "rando_util"
version = "0.1.0"
authors = ["berylliosis <berylliumninja@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rando_parser = { path = "../rando_parser" }
petgraph = "0.5.1"