[package]
name = "rando_core"
version = "0.1.0"
authors = ["berylliosis <berylliumninja@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
codespan-reporting = "0.11.1"
either = "1.6.1"