[package]
name = "rando_parser"
version = "0.1.0"
authors = ["berylliosis <berylliumninja@gmail.com>"]
edition = "2021"

[dependencies]
nom = "7.1.0"
lalrpop-util = { version = "0.19.4", features = ["lexer"] }
regex = "1"
lazy_static = "1.4.0"
assert_matches = "1.5.0"